name: QMKJB000_bcell_ranalysis0.1.0
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - igblast=1.10.0
  - bioconda::phylip=3.697
  - conda-forge::r-base=4.0.2
  - conda-forge::r-alakazam=1.0.2
  - bioconda::r-shazam=0.2.3
  - bioconda::r-tigger=0.4.0
  - conda-forge::r-dplyr=1.0.2
  - conda-forge::r-data.table=1.12.8
  - conda-forge::r-igraph=1.2.5
  - conda-forge::r-gplots=3.1.0
  - conda-forge::r-circlize=0.4.10
  - conda-forge::r-upsetr=1.4.0
  - conda-forge::r-gtools=3.8.2
  - conda-forge::r-ggplot2=3.3.2
  - conda-forge::r-svglite=1.2.3.2
  - conda-forge::r-extrafont=0.17
  - conda-forge::r-optparse=1.6.6
  - conda-forge::r-airr=1.3.0
  - conda-forge::r-stringr=1.4.0
